### ISSUE TITLE
Search query not allowing multiple exclusions

### ISSUE THREAD

**Issue by nickyoung87** [sureswiftcapital/Simple-Calendar#248]
https://wordpress.org/support/topic/combine-negative-queries/

**Comment by damonsharp** [comment]
I spent a little time testing this today with different query parameters given the following events...

Title: Test Event
Where: The Interwebs
Date: Aug. 15-19 (repeating)
Time: 10-11am EST
Description: N/A

Title: Test exclusion of search title
Where: Online
Date: Aug. 18
Time: 3-4pm EST
Description: N/A

Title: Billy Bob search exclusion test.
Where: Online
Date: Aug. 21
Time: 1-2pm EST
Description: N/A

Title: Damon's Test Meeting
Where: N/A
Date: Aug. 19
Time: all day
Description: N/A

The following search parameters entered into the individual calendar settings under Google Calendar > Search Query return no matching results (calendar is empty)...

Bob-Damon
Bob -Damon
"Bob"-"Damon"
"Bob" -"Damon"
-Bob -Damon
-"Bob" -"Damon"
-"Bob" -"Damon"
-"Damon"-"Bob"

I thought initially that url encoding may be an underlying issue, but have tried both `rawurlencode` (the current way that it is encoded) as well as `urlencode` on line 403 of release 3.1.9 without any differences.

I'm in the process of still investigating this and will do further testing at a later date.

**Comment by damonsharp** [comment]
@zachwills Looks like the above issue is how it's supposed to work after additional testing. I updated the SimpleCalendar documentation to clarify negative search queries per below. I believe this can be closed out.

Multiple negative keywords can be used as well. To exclude the words camping & supplies for example, use -camping -supplies as the search terms. If you want to exclude phrases, use double quotes around the entire phrase, single quotes around words, and + to combine them into one phrase. To exclude the phrase "camping supplies" for example, enter the following: -"‘something’+’else'". Note that using -"camping supplies" will exclude the words camping and supplies, which is basically the same as using -camping -supplies.

See https://docs.simplecalendar.io/google-calendar-search-queries/
