### ISSUE TITLE
3.1.12 release seems to have a broken composer config

### ISSUE THREAD

**Issue by KZeni** [sureswiftcapital/Simple-Calendar#323]
This is mentioned with details at https://wordpress.org/support/topic/help-immediate-update-to-3-1-21-took-down-my-website-just-now/. Figured I'd also post it here for better visibility depending on where people look for updates.

This really needs to be fixed since it's a fatal error taking sites down that have updated. Also, this type of problem should really be avoided with a high priority due to the fact that sites that auto-update may have an issue updating to the fixed version released after the fact due to the server error that the problematic version caused.

**Comment by zachwills** [comment]
Thanks for reporting this - we're working on the fix as we speak and should have it out shortly this morning.

**Comment by zachwills** [comment]
For now we removed the 3.1.21 version of the plugin and released 3.1.22 which contains the 3.1.20 code. This should allow users to auto update to the version without any issues as well as prevent anybody from downloading the version with the fatal error. Let me know if you have any issues getting the plugin activated again.

We'll be updating our testing and QA process to ensure that an issue like this doesn't make it's way to our users again. Sorry about this issue -- thank you for being a user and supporting Simple Calendar!
