### ISSUE TITLE
3.1.21 - PHP Fatal error

### ISSUE THREAD

**Issue by kalich5** [sureswiftcapital/Simple-Calendar#324]
Warning: require(/home/vu009026/www/wp-content/plugins/google-calendar-events/vendor/composer/../react/promise/src/functions_include.php): failed to open stream: No such file or directory in /home/vu009026/www/wp-content/plugins/google-calendar-events/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/home/vu009026/www/wp-content/plugins/google-calendar-events/vendor/composer/../react/promise/src/functions_include.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/vu009026/www/wp-content/plugins/google-calendar-events/vendor/composer/autoload_real.php on line 66

**Comment by zachwills** [comment]
Thanks for reporting this - we're working on the fix as we speak and should have it out shortly this morning.

**Comment by zachwills** [comment]
For now we removed the 3.1.21 version of the plugin and released 3.1.22 which contains the 3.1.20 code. This should allow users to auto update to the version without any issues as well as prevent anybody from downloading the version with the fatal error. Let me know if you have any issues getting the plugin activated again.

We'll be updating our testing and QA process to ensure that an issue like this doesn't make it's way to our users again. Sorry about this issue -- thank you for being a user and supporting Simple Calendar!
