### ISSUE TITLE
Plugin size optimization

### ISSUE THREAD

**Issue by kalich5** [sureswiftcapital/Simple-Calendar#335]
I have a question, the plugin is terribly big. Mainly because of the folder: google-calendar-events \ vendor \ google \ apiclient \ src \ Google \

It occurs to me that everything is there and there are useless things. Mainly in this folder: d: \ DOWNLOAD \ google-calendar-events \ vendor \ google \ apiclient \ src \ Google \ Service \

Why do we have service for Classrom, YouTube and more? By reducing these nonsense, the size of the plugin could be reduced by 2/3.

**Comment by nickyoung87** [comment]
We have just fixed this in 3.1.33 and are now only including the necessary libraries needed.
