### ISSUE TITLE
Fatal error: autoupload_real.php file missing

### ISSUE THREAD

**Issue by eshenayo** [sureswiftcapital/Simple-Calendar#336]
I had to disable the plugin after updating to the newest version:

**Plugin Version:**  3.1.32

**PHP version:** 7.2

**WordPress Version:** 5.5.1

**Error:** `Fatal error: require_once(): Failed opening required 'wp-content/plugins/google-calendar-events/vendor/composer/autoload_real.php' (include_path='.:/opt/alt/php72/usr/share/pear') in wp-content/plugins/google-calendar-events/vendor/autoload.php on line 5`

**Comment by nickyoung87** [comment]
Hi,

Sorry for the issue, could you please update to 3.1.33 and see if the problem is resolved?

Thanks!

**Comment by eshenayo** [comment]
Thank you for the update. I updated to the latest plugin version (3.1.33) and it does solve the issue. A note, I had to upgrade my version of PHP from 7.2 to 7.4 otherwise, I could not upgrade: There is a new version of Simple Calendar available, but it doesn’t work with your version of PHP.
