### ISSUE TITLE
Library conflict - guzzlehttp

### ISSUE THREAD

**Issue by ahall41** [sureswiftcapital/Simple-Calendar#337]
I'm getting this error (from another plugin - one of my own):
`Uncaught Error: Undefined class constant 'VERSION' in /var/www/ddalive/wp-content/plugins/google-calendar-events/vendor/guzzlehttp/guzzle/src/functions.php:136`
It seems to be generated by a conflict between the versions of guzzlehttp (yours is 6.5.5. mine is 7.0.1). Perhaps the line _include_once 'vendor/autoload.php'_ should be deferred until the plugin code is actually invoked rather than loaded?

**Comment by nickyoung87** [comment]
The guzzlehttp library has been updated in version 3.1.33, thanks for bringing this up.
