### ISSUE TITLE
The plugin is incompatible with other Google-using plugins

### ISSUE THREAD

**Issue by marekdedic** [sureswiftcapital/Simple-Calendar#341]
Hi,
I am the author of the [Image and video gallery from Google Drive](https://wordpress.org/plugins/skaut-google-drive-gallery/) plugin. I just wanted to let you know that your plugin is unfortunately incompatible with other plugins using the Google API. You include the Google API files (parts of your vendor folder basically), however, you leave all the files "un-prefixed". If any other plugin does so, it breaks because of double-defining classes.

I found this out because of a clash with our plugin (that is also caused by a mistake on our side, which should be fixable). A way out of this mess is to put all of your vendor code into a custom namespace so that there is no clash if multiple instances of one dependency are included. To see how we did it, you can look [here](https://github.com/skaut/skaut-google-drive-gallery/blob/master/gulpfile.js#L36-L299) (However, I think we are a bit too aggressive with pruning unused code, which leads to a slightly brittle implementation)

**Comment by kalich5** [comment]
@nickyoung87 This is a big problem! Dozens of websites are no longer working for us!

**Comment by kalich5** [comment]
@nickyoung87 Your wrong Google API connection is blocking another plugin! UpdraftPlus does not currently send site backups to Google Drive. I ask you for an immediate remedy!

**Comment by nickyoung87** [comment]
This is now at the top of the list of things to work on.

**Comment by kalich5** [comment]
I hope it will be fixed as soon as possible. It's quite restrictive!

**Comment by mickwall001** [comment]
I have fixed this in my local environment, I am going to try and get it into git - Nickyoung87 if you are able to help me I can send you a zip file - please reach out.

I have used php-scoper to create scoped versions of all the dependencies which means this won't conflict with anything.

the change will break the add-ons so those will need changing - again I have those changes complete.

**Comment by nickyoung87** [comment]
Thank you for this @mickwall001!

@kalich5 or @marekdedic Have you happened to test out the PR to see if it fixes it for you? I will be going through that today to do some testing, but the more eyes the better :)

**Comment by marekdedic** [comment]
Hi,
no, we fixed our plugin on our side, so there no longer is a collision (Although there might be one with Updraft and its Google Drive backup if you want something to test against)

Hyey, @mickwall001, thanks for the tip with php-scoper! I might be able to replace an enormous gulpfile with regexes with it :D
